services:
  - type: web
    name: taskflow-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://taskflow-frontend-brown-psi.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,PATCH,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Authorization,X-Requested-With,Accept
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"